/* ═══ vocab-seed-2.js — 詞庫種子·第二批（共 229 條） ═══
   音樂人162（小提琴45｜鋼琴40｜大提琴18｜指揮30｜樂團12｜作曲家17）
   ＋補充67（表情15｜力度8｜速度12｜音質10｜室內樂8｜音樂廳8｜比賽6）
   想加改刪唔使掂呢個檔——喺 App 詞庫頁做，自動存落 private repo */
window.VOCAB_SEED_2=(()=>{
const T=[];
const add=(cat,a)=>a.forEach(([zh,en,tag,desc])=>T.push({cat,zh,en,tag:tag||'',desc:desc||''}));

/* ── 音樂人 162 ── */
add('音樂人',[
['海菲茲','Jascha Heifetz','小提琴','美俄學派；技術完美標杆'],
['克萊斯勒','Fritz Kreisler','小提琴','維也納風歌唱；小品大師'],
['奧伊斯特拉赫','David Oistrakh','小提琴','俄學派；溫厚宏亮'],
['柯岡','Leonid Kogan','小提琴','俄學派；精準冷冽'],
['梅紐因','Yehudi Menuhin','小提琴','神童；人文深度'],
['米爾斯坦','Nathan Milstein','小提琴','俄學派；貴族式乾淨'],
['帕爾曼','Itzhak Perlman','小提琴','歌唱性與溫暖音色'],
['穆特','Anne-Sophie Mutter','小提琴','卡拉揚提攜；音色多變'],
['哈恩','Hilary Hahn','小提琴','精準與結構感；技術示範級'],
['貝爾','Joshua Bell','小提琴','美式浪漫歌唱'],
['祖克曼','Pinchas Zukerman','小提琴','兼中提琴；敦厚'],
['克雷默','Gidon Kremer','小提琴','智性；冷門曲目推手'],
['謝霖','Henryk Szeryng','小提琴','法比學派；典雅紮實'],
['格魯米歐','Arthur Grumiaux','小提琴','法比學派；乾淨華美'],
['內芙','Ginette Neveu','小提琴','法國；熾熱悲壯'],
['蒂博','Jacques Thibaud','小提琴','法蘭西學派奠基'],
['艾爾曼','Mischa Elman','小提琴','俄學派；濃郁揉音'],
['莫里尼','Erica Morini','小提琴','維也納傳統'],
['費拉斯','Christian Ferras','小提琴','法國；戲劇性'],
['雷諾·卡普松','Renaud Capuçon','小提琴','法國當代'],
['格拉佩利','Stéphane Grappelli','小提琴','爵士小提琴傳奇'],
['米多莉','Midori Gotō','小提琴','五嶋綠；美籍日裔'],
['諏訪內晶子','Akiko Suwanai','小提琴','柴賽首獎；細膩'],
['莊司紗矢香','Sayaka Shoji','小提琴','日裔；帕格尼尼金獎'],
['茱莉亞·費舍爾','Julia Fischer','小提琴','德國；全料型'],
['穆洛娃','Viktoria Mullova','小提琴','俄→西；多風格探索'],
['浮士德','Isabelle Faust','小提琴','德國；古樂觸覺'],
['魏特哈斯','Antje Weithaas','小提琴','德國；結構嚴謹'],
['齊默爾曼','Frank Peter Zimmermann','小提琴','德國；智性精密'],
['卡瓦科斯','Leonidas Kavakos','小提琴','希臘；西貝流士大賽冠軍'],
['文格洛夫','Maxim Vengerov','小提琴','俄；炫技與戲劇'],
['列賓','Vadim Repin','小提琴','俄；柴賽最年輕金牌'],
['齊奈德','Nikolaj Znaider','小提琴','丹麥；兼指揮'],
['埃內斯','James Ehnes','小提琴','加拿大；技術教科書'],
['陳銳','Ray Chen','小提琴','台裔澳籍；网络世代'],
['金本索里','Bomsori Kim','小提琴','韓國；音色亮麗'],
['波杰','Rachel Podger','小提琴','巴洛克小提琴；巴哈權威'],
['佐藤俊介','Shunske Sato','小提琴','巴洛克＋現代雙修'],
['伊薩伊','Eugène Ysaÿe','小提琴','法比學派；六首無伴奏奏鳴曲'],
['西蓋蒂','Joseph Szigeti','小提琴','匈牙利學派；智識型'],
['弗萊什','Carl Flesch','小提琴','教學體系；音階系統'],
['維尼奧夫斯基','Henri Wieniawski','小提琴','學派；兩首協奏曲'],
['約阿希姆','Joseph Joachim','小提琴','德奧學派；布拉姆斯摯友'],
['埃內斯柯','George Enescu','小提琴','羅馬尼亞；全才'],
['魯賓斯坦','Artur Rubinstein','鋼琴','波蘭；蕭邦代言人'],
['霍洛維茲','Vladimir Horowitz','鋼琴','俄→美；超技浪漫'],
['李赫特','Sviatoslav Richter','鋼琴','俄；規模感巨人'],
['吉列爾斯','Emil Gilels','鋼琴','俄；鋼鐵音粒'],
['米開朗傑里','A.B. Michelangeli','鋼琴','意大利；音色煉金'],
['波里尼','Maurizio Pollini','鋼琴','意大利；理性精密'],
['阿格麗希','Martha Argerich','鋼琴','阿根廷；熾烈即興'],
['阿勞','Claudio Arrau','鋼琴','智利；深沉宏大'],
['魯道夫·塞爾金','Rudolf Serkin','鋼琴','德奧傳統'],
['霍夫曼','Josef Hofmann','鋼琴','歷史錄音傳奇'],
['拉赫曼尼諾夫','Sergei Rachmaninoff','鋼琴','兼作曲；演奏宏偉'],
['科爾托','Alfred Cortot','鋼琴','法國；詩意（指法多錯音）'],
['吉澤金','Walter Gieseking','鋼琴','法國印象派權威'],
['肯普夫','Wilhelm Kempff','鋼琴','德國；貝多芬舒伯特'],
['巴克豪斯','Wilhelm Backhaus','鋼琴','德國；布拉姆斯'],
['艾德溫·費雪','Edwin Fischer','鋼琴','德國；巴哈莫扎特'],
['魯普','Radu Lupu','鋼琴','羅馬尼亞；內斂如歌'],
['佩拉希亞','Murray Perahia','鋼琴','美國；透明歌唱'],
['齊瑪曼','Krystian Zimerman','鋼琴','波蘭；自帶樂團指揮'],
['布倫德爾','Alfred Brendel','鋼琴','德奧；結構詮釋家'],
['安德拉斯·席夫','András Schiff','鋼琴','匈牙利；巴哈全集'],
['內田光子','Mitsuko Uchida','鋼琴','莫扎特；通透'],
['霍夫','Stephen Hough','鋼琴','英國；兼作曲'],
['古爾德','Glenn Gould','鋼琴','加拿大；巴哈哥德堡'],
['布尼亞季什維利','Khatia Buniatishvili','鋼琴','格魯吉亞；戲劇性'],
['王羽佳','Yuja Wang','鋼琴','超技；曲目驚人'],
['郎朗','Lang Lang','鋼琴','普及推廣影響力大'],
['張昊辰','Haochen Zhang','鋼琴','范·克萊本金獎'],
['基辛','Evgeny Kissin','鋼琴','俄；神童超技'],
['普列特涅夫','Mikhail Pletnev','鋼琴','兼指揮作曲'],
['索科洛夫','Grigory Sokolov','鋼琴','俄；現場變奏大師'],
['沃洛多斯','Arcadi Volodos','鋼琴','改編曲超技'],
['萊昂斯卡婭','Elisabeth Leonskaja','鋼琴','俄→奧'],
['安斯涅','Leif Ove Andsnes','鋼琴','挪威；北歐曲目'],
['薩瑪森·弗朗索瓦','Samson François','鋼琴','法國；德布西拉威爾'],
['卡薩德絮','Robert Casadesus','鋼琴','法國家族'],
['里帕蒂','Dinu Lipatti','鋼琴','羅馬尼亞；純淨典範'],
['拉羅查','Alicia de Larrocha','鋼琴','西班牙曲目權威'],
['傅聰','Fou Ts\'ong','鋼琴','蕭邦詩人；家書之子'],
['尼古拉耶娃','Tatiana Nikolayeva','鋼琴','蕭士塔高維奇前奏曲賦格'],
['卡薩爾斯','Pablo Casals','大提琴','現代大提琴之父'],
['富尼埃','Pierre Fournier','大提琴','法國；貴族優雅'],
['托特利耶','Paul Tortelier','大提琴','法國；巴哈全套'],
['史塔克','János Starker','大提琴','匈牙利；技術權威'],
['羅斯特羅波維奇','M. Rostropovich','大提琴','俄；多部協奏曲題獻'],
['馬友友','Yo-Yo Ma','大提琴','跨界廣博'],
['伊瑟利斯','Steven Isserlis','大提琴','英國；音色毛絨'],
['王健','Jian Wang','大提琴','內斂歌唱'],
['麥斯基','Mischa Maisky','大提琴','俄→以；浪漫濃烈'],
['杜普蕾','Jacqueline du Pré','大提琴','艾爾加；熾烈傳奇'],
['讓德龍','Maurice Gendron','大提琴','法國；教學權威'],
['海因里希·希夫','Heinrich Schiff','大提琴','奧地利；兼指揮'],
['加蒂爾·卡普松','Gautier Capuçon','大提琴','法國當代'],
['沙夫蘭','Daniil Shafran','大提琴','俄；纖細揉音'],
['格林豪斯','Bernard Greenhouse','大提琴','美藝三重奏創始'],
['楊文信','Wen-Sinn Yang','大提琴','台裔；慕尼黑愛樂首席'],
['秦立巍','Li-Wei Qin','大提琴','柴賽銀獎'],
['卡尼漢-美臣','Sheku Kanneh-Mason','大提琴','英國新世代'],
['卡拉揚','Herbert von Karajan','指揮','柏林愛樂王朝；音色光澤'],
['伯恩斯坦','Leonard Bernstein','指揮','美國；紐約愛樂'],
['阿巴多','Claudio Abbado','指揮','意大利；通透當代'],
['穆蒂','Riccardo Muti','指揮','意大利；歌劇傳統'],
['夏伊','Riccardo Chailly','指揮','意大利；米蘭威爾第'],
['杜達美','Gustavo Dudamel','指揮','委內瑞拉系統教育奇蹟'],
['楊頌斯','Mariss Jansons','指揮','巴伐利亞廣播；暖厚'],
['海丁克','Bernard Haitink','指揮','荷蘭；布魯克納馬勒'],
['康德拉申','Kirill Kondrashin','指揮','俄；拉赫合作'],
['穆拉文斯基','Yevgeny Mravinsky','指揮','列寧格勒愛樂半世紀'],
['羅日傑斯特文斯基','G. Rozhdestvensky','指揮','俄；曲目驚人'],
['滕斯泰特','Klaus Tennstedt','指揮','馬勒狂熱'],
['蕭提','Georg Solti','指揮','芝加哥王朝；匈牙利'],
['克倫佩勒','Otto Klemperer','指揮','德奧；莊重宏偉'],
['富特文格勒','W. Furtwängler','指揮','德國；即興式時間魔法'],
['托斯卡尼尼','Arturo Toscanini','指揮','意大利；忠譜紀律鼻祖'],
['華爾特','Bruno Walter','指揮','馬勒弟子；維也納溫暖'],
['賽爾','George Szell','指揮','克利夫蘭鍛造者'],
['萊納','Fritz Reiner','指揮','芝加哥；精準鞭法'],
['孟許','Charles Munch','指揮','法國；熾熱色彩'],
['巴比羅利','John Barbirolli','指揮','英國；艾爾加沃恩威廉'],
['馬里納','Neville Marriner','指揮','聖馬丁室內樂團創始'],
['加德納','John Eliot Gardiner','指揮','HIP；巴哈清唱劇全套'],
['諾靈頓','Roger Norrington','指揮','HIP；無揉音實驗'],
['布呂根','Frans Brüggen','指揮','HIP；直笛大師轉指揮'],
['哈農庫特','Nikolaus Harnoncourt','指揮','HIP 先驅；古樂運動旗手'],
['霍格伍德','Christopher Hogwood','指揮','HIP；古樂學院派'],
['薩瓦利什','Wolfgang Sawallisch','指揮','德奧歌劇'],
['馬捷爾','Lorin Maazel','指揮','超技讀譜'],
['普列文','André Previn','指揮','兼電影配樂爵士'],
['柏林愛樂','Berliner Philharmoniker','樂團','世界頂級；數位音樂廳'],
['維也納愛樂','Wiener Philharmoniker','樂團','金色大廳新年音樂會'],
['倫敦交響樂團','London Symphony Orch.','樂團','自管自制；錄音量巨大'],
['皇家音樂廳管弦樂團','Royal Concertgebouw Orch.','樂團','阿姆斯特丹；馬勒傳統'],
['芝加哥交響樂團','Chicago Symphony Orch.','樂團','銅管之王'],
['費城管弦樂團','Philadelphia Orchestra','樂團','費城之聲'],
['紐約愛樂','New York Philharmonic','樂團','美國最老'],
['波士頓交響樂團','Boston Symphony Orch.','樂團','Tanglewood 夏日營'],
['克利夫蘭管弦樂團','Cleveland Orchestra','樂團','精準透明'],
['巴伐利亞廣播交響樂團','BR Symphonieorchester','樂團','楊頌斯王朝'],
['聖彼得堡愛樂','St. Petersburg Phil.','樂團','前列寧格勒愛樂'],
['香港管弦樂團','Hong Kong Philharmonic','樂團','本地；長期駐團'],
['巴赫','J.S. Bach','作曲家','無伴奏奏鳴曲組曲；雙協奏曲'],
['莫扎特','W.A. Mozart','作曲家','五首協奏曲；奏鳴曲'],
['貝多芬','Beethoven','作曲家','十首奏鳴曲；協奏曲'],
['布拉姆斯','Brahms','作曲家','三首奏鳴曲；協奏曲'],
['孟德爾頌','Mendelssohn','作曲家','e小調協奏曲'],
['舒伯特','Schubert','作曲家','幻想曲；奏鳴曲'],
['舒曼','Schumann','作曲家','奏鳴曲；幻想曲'],
['帕格尼尼','Paganini','作曲家','24 首隨想曲；協奏曲'],
['布魯赫','Max Bruch','作曲家','g小調協奏曲；蘇格蘭幻想曲'],
['柴可夫斯基','Tchaikovsky','作曲家','D大調協奏曲'],
['西貝流士','Sibelius','作曲家','d小調協奏曲'],
['德伏札克','Dvořák','作曲家','a小調協奏曲；四首小品'],
['聖桑','Saint-Saëns','作曲家','第三協奏曲；引子與迴旋'],
['法朗克','César Franck','作曲家','A大調奏鳴曲'],
['德布西','Debussy','作曲家','g小調奏鳴曲'],
['拉威爾','Ravel','作曲家','茨岡；F大調奏鳴曲'],
['巴爾托克','Bartók','作曲家','羅馬尼亞舞曲；獨奏奏鳴曲']
]);

/* ── 補充 67 ── */
add('表情記號',[
['dolce','dolce','','柔美甜美'],
['espressivo','espressivo','','富表情，傾瀉情感'],
['cantabile','cantabile','','如歌唱般'],
['grazioso','grazioso','','優雅輕盈'],
['agitato','agitato','','激動不安'],
['maestoso','maestoso','','莊嚴宏偉'],
['dolente','dolente','','哀傷悲嘆'],
['appassionato','appassionato','','熱情如火'],
['tranquillo','tranquillo','','平靜安寧'],
['vivace','vivace','','活潑有生氣'],
['scherzando','scherzando','','詼諧嬉戲'],
['teneramente','teneramente','','溫柔體貼'],
['furioso','furioso','','狂暴激烈'],
['sereno','sereno','','明朗晴空'],
['misterioso','misterioso','','神秘幽深']
]);

add('力度記號',[
['ppp','pianississimo','力度','幾乎聽唔到；弓貼指板'],
['pp','pianissimo','力度','很弱'],
['p','piano','力度','弱'],
['mp','mezzo-piano','力度','中弱'],
['mf','mezzo-forte','力度','中強'],
['f','forte','力度','強'],
['ff','fortissimo','力度','很强'],
['fff','fortississimo','力度','全弓放盡；近琴橋']
]);

add('速度術語',[
['莊板','Grave','','沉重莊嚴；極慢'],
['廣板','Largo','','寬廣緩慢'],
['緩板','Lento','','慢'],
['柔板','Adagio','','從容柔緩'],
['小行板','Andantino','','略快過行板'],
['小快板','Allegretto','','略慢過快板'],
['最急板','Prestissimo','','最快極限'],
['漸快','accelerando','','逐漸加快'],
['漸慢','ritardando','','逐漸減慢'],
['回原速','a tempo','','回復原本速度'],
['稍慢','meno mosso','','流動慢啲'],
['稍快','più mosso','','流動快啲']
]);

add('音質',[
['單聲道','mono','','1930–50s 主流；中置聲場'],
['立體聲','stereo','','左右分道'],
['早期立體聲','early stereo','','1958–60s；聲場未成熟'],
['類比錄音','analogue','','磁帶模擬；溫潤'],
['數位錄音','digital','','1980s 後主流'],
['DDD','DDD','','全數位製作'],
['ADD','ADD','','類比錄音數位母帶'],
['AAD','AAD','','類比錄音混音'],
['高解析音源','hi-res','','24bit/96k+；細節最豐'],
['現場直播音源','live broadcast','','電台直播存檔；年代感']
]);

add('室內樂',[
['弦樂三重奏','string trio','','小中大提琴各一'],
['鋼琴四重奏','piano quartet','','鋼琴＋弦樂三件'],
['弦樂五重奏','string quintet','','多一件中提琴或大提琴'],
['單簧管五重奏','clarinet quintet','','單簧管＋弦樂四件'],
['弦樂六重奏','string sextet','','兩兩三聲部'],
['木管五重奏','wind quintet','','長雙簧單簧巴松＋圓號'],
['銅管五重奏','brass quintet','','二小號圓號長號大號'],
['弦樂八重奏','string octet','','雙四重奏對話']
]);

add('音樂廳',[
['卡內基音樂廳','Carnegie Hall','美國紐約','首演聖地'],
['維也納金色大廳','Musikverein','奧地利維也納','新年音樂會主场'],
['柏林愛樂廳','Berliner Philharmonie','德國柏林','葡萄園式聲學'],
['阿姆斯特丹音樂廳','Concertgebouw','荷蘭阿姆斯特丹','音效世界級'],
['波士頓交響大廳','Symphony Hall','美國波士頓','鞋盒聲學典範'],
['皇家節日廳','Royal Festival Hall','英國倫敦','南岸中心'],
['三得利音樂廳','Suntory Hall','日本東京','亞洲頂級'],
['香港文化中心音樂廳','HK Cultural Centre','香港尖沙咀','本地主場']
]);

add('比賽',[
['伊莉莎白女王大賽','Queen Elisabeth Competition','比利時','小提琴鋼琴輪替'],
['柴可夫斯基大賽','Tchaikovsky Competition','俄羅斯','四大賽之一'],
['帕格尼尼大賽','Paganini Competition','意大利熱那亞','小提琴金獎傳統'],
['維尼奧夫斯基大賽','Wieniawski Competition','波蘭','小提琴專項'],
['梅紐因大賽','Menuhin Competition','國際巡迴','青少年小提琴'],
['蕭邦大賽','Chopin Competition','波蘭華沙','五年一屆鋼琴']
]);

return T;
})();
